name: lab1
on: [push]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: echo "Hello, World!"
      - run: pip install nbconvert ipykernel matplotlib pint scipy numpy open-atmos-jupyter-utils
      - uses: actions/checkout@v4
      - run: brew install pandoc basictex inkscape
      - run: sudo tlmgr update --self && sudo tlmgr install collection-xetex
      - run: python -m nbconvert --to pdf --execute lab1/lab1.ipynb
      - uses: actions/upload-artifact@v4
        with:
          name: lab1
          path: lab1/lab1.pdf
