name: lab3
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pip install nbconvert ipykernel matplotlib pint scipy numpy open-atmos-jupyter-utils
      - uses: actions/checkout@v4
      - run: sudo apt-get install pandoc texlive-xetex inkscape
      - run: python -m nbconvert --to pdf --execute lab3/lab3.ipynb
      - uses: actions/upload-artifact@v4
        with:
          name: lab3
          path: lab3/lab3.pdf