name: lab6
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip install nbconvert ipykernel matplotlib pint numpy open-atmos-jupyter-utils scipy
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex inkscape
      - uses: actions/checkout@v4
      - run: python -m nbconvert --to pdf --execute lab6/lab6.ipynb
      - uses: actions/upload-artifact@v4
        with:
          name: lab6
          path: lab6/lab6.pdf